<Project>
  <PropertyGroup>
    <OutputPath>$(MSBuildThisFileDirectory)Bin\$(Configuration)\</OutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>
