<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App4di.Dotnet.UserManager.Application\App4di.Dotnet.UserManager.Application.csproj" />
    <ProjectReference Include="..\App4di.Dotnet.UserManager.Domain\App4di.Dotnet.UserManager.Domain.csproj" />
  </ItemGroup>

</Project>
