<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>App4di.Dotnet.UserManager.ViewModel</RootNamespace>
    <AssemblyName>App4di.Dotnet.UserManager.ViewModel</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App4di.Dotnet.UserManager.Core\App4di.Dotnet.UserManager.Core.csproj" />
    <ProjectReference Include="..\App4di.Dotnet.UserManager.Model\App4di.Dotnet.UserManager.Model.csproj" />
    <ProjectReference Include="..\FirstParty\FW4di.Dotnet.Core\Project\FW4di.Dotnet.Core\FW4di.Dotnet.Core.csproj" />
  </ItemGroup>

</Project>
